### ISSUE TITLE
Dependency on  node-sass outdated cannot install sass-brunch on windows10 x64

### ISSUE THREAD

**Issue by ser1us** [brunch/sass-brunch#128]
Hi there!

I noticed today that I cannot install sass-brunch anymore on my machine. The reason seems to be the node-sass package v 3.8.x dependency.

My installation fails with the following message: 
```Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-51_binding.node"```

The latest version (and some versions earlier) seems to have this this 51 file.
```https://github.com/sass/node-sass/releases/download/v3.13.0/win32-x64-51_binding.node```

Cheers,
Christoph

**Comment by denysdovhan** [comment]
@ser1us hi! What the version of `sass-brunch` are you using?

Current version of `sass-brunch` uses `node-sass@^4.0.0`. Probably, you're using the old version of the plugin.

**Comment by johanalkstal** [comment]
The problem is that the file it is trying to download is missing from GitHub.

Even if I install the latest version of `sass-brunch`, it tries to download `node-sass 3.8.0`.

**Comment by shvaikalesh** [comment]
Does version from `master` work OK?

**Comment by johanalkstal** [comment]
Yes, `master` works because it has `node-sass: ~4.0.0` while ´2.9.0` has `node-sass: ~3.8.0`.

**Comment by shvaikalesh** [comment]
We will release `sass-brunch` as soon as fix interop with `postcss`

**Comment by ser1us** [comment]
sorry @denysdovhan for the late response. master works fine for me :) thanks for the fix.

**Comment by paulmillr** [comment]
you can use sass-brunch 2.10.4 instead of master

**Comment by a00andos** [comment]
I still experience this problem when installing from npm: Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

You say I can use sass-brunch 2.10.4 instead of master, but thats the version currently on npm, and it still doesn't work for me.

**Comment by kotsius** [comment]
This issue is still alive and well in 2018. As a newbie, it took me over an hour to figure out how to circumvent it. Version 2.10.4 does not install on my Windows 10 machine using npm the usual way, as it still asks for v3.8.0 of node-sass (postinstall), which cannot be found. I tried with both v8 and v9 of Node.js, by the way. For the sake of explicitness, this was the solution that worked:

npm install --save-dev https://github.com/brunch/sass-brunch.git

**Comment by illyas3** [comment]
I have the same issue when running `npm install`. It tries to download `https://github.com/sass/node-sass/releases/download/v3.8.0/<SYSTEM>.node`. Tested with ubuntu 16.04, rasbian stretch, macOS 10.12.16, binaries don't exist at the destination thus getting similar error. The problem is with the node-sass version.

So I checked the npm registry, and it seems that [sass-brunch ](https://registry.npmjs.org/sass-brunch/)v2.10.4 still depends on node-sass version 3.8.0 in the registry, while in master its v4.5.3.

Can npm registry be updated to match the master please?

**Comment by TomRK1089** [comment]
It's been over a year since this issue was reported. I am regretfully depending on the master branch directly from GitHub, but this is not our organization's typical policy as it complicates reproducible builds. 

What specific items are blocking a proper release of the `master` branch to NPM?

**Comment by asheehan** [comment]
I'm actually getting this error even when using `npm install --save-dev https://github.com/brunch/sass-brunch.git`

```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node": 

HTTP error 404 Not Found
```

**Comment by MeerKatDev** [comment]
Problem still there, same error as above
