### ISSUE TITLE
Files with underscores compiled?

### ISSUE THREAD

**Issue by cjamison** [brunch/sass-brunch#152]
I had thought that files with underscores were not compiled. However, using version 2.10.4, I have files with underscores (e.g., `_global.scss`) that are being compiled. I even put them in a directory with an underscore but that did not help. 

These files are in a directory hierarchy that brunch is watching; however, I thought these would be ignored. When I include these in my "main" file the CSS gets duplicated (once because the file itself is compiled and again because it is included in the main file). Is this a bug? Or, do I not understand how this should work?

**Comment by max-scopp** [comment]
I am aware of this error and just looked into it.

It's _not really_ a sass-brunch error, brunch itself calls the Plugin in order to compile that file, but since brunch doesn't know that the file is a sass-submodule, the internal node-sass package fails to compile.

The following commit would fix the plugin, creating pull request soon.
https://github.com/max-scopp/sass-brunch/commit/cc6f0bac1509b12133a49a1839ea871095faf900

You can use my `sass-brunch` version, since I rarely see activity here and I don't think this will be merged soon.

My version is also a bit more compatible with post-processors like css-next.
Hope this helps you.

**Comment by denysdovhan** [comment]
https://github.com/max-scopp/sass-brunch/commit/cc6f0bac1509b12133a49a1839ea871095faf900 LGTM 👍🏻

**Comment by shvaikalesh** [comment]
Not cool to check for `_`. This should be configurable by `conventions.ignored`.

**Comment by J-Kallunki** [comment]
Please default to ignore `_*.scss` and make it configurable.

**Comment by lightcap** [comment]
Just spent a few hours pulling my hair out over this one. It really would be great to ignore `_` files, agreed.
