### ISSUE TITLE
Sass glob import

### ISSUE THREAD

**Issue by GesJeremie** [brunch/sass-brunch#97]
Is it possible to introduce in this plugin a "glob" import ? 

Something like: 

``` sass
@import 'components/*'
```

Kind regards,

Jérémie

**Comment by paulmillr** [comment]
Yes, let's keep this open.

**Comment by nathamanath** [comment]
Hi,

I had a go at implementing this [here](https://github.com/nathamanath/sass-brunch/blob/feature/native_mode_globbing/index.js) in native mode only using the `node-sass-globbing` package. It seems to get the job done.

I also looked at using the gem `sass-globbing` to achieve this in ruby mode also, but hit problems when compiling sass with it via stdin [see issue](https://github.com/chriseppstein/sass-globbing/issues/36).

Any thoughts on this?

**Comment by nathamanath** [comment]
HI again, Having had chance to test this in more thoroughly, work is needed on watching files imported via glob. It is importing the file correctly, however, It does not watch the file correctly. I will have another go at this soon

**Comment by shvaikalesh** [comment]
Add `globDeps: true` [here](https://github.com/es128/progeny/blob/master/index.js#L33)

**Comment by nathamanath** [comment]
Thanks @shvaikalesh, just tried it locally and it works :)

**Comment by nathamanath** [comment]
Ok, so @es128 at progeny suggested that this should be done by configuration rather than changing defaults as sass does not support this feature natively.

So, I have updated progeny version to latest, and added `globDeps` config [here](https://github.com/nathamanath/sass-brunch/blob/feature/native_mode_globbing/index.js#L93). Works well :)

I don't know if this should this be done for `seekCompass` as well?
